// Package githubclient provides helpers for interacting with GitHub repositories,
// including automated pull request creation workflows.
package githubclient

// Copyright (c) 2026 SanDevil23
// SPDX-License-Identifier: Apache-2.0	

import (
	"context"
	"log"

	"github.com/google/go-github/v62/github"
)

// CreatePR creates a new branch from the main branch, commits the provided
// files to that branch, and opens a pull request against main.
//
// Parameters:
//   - ctx: context for request cancellation and timeouts.
//   - client: authenticated GitHub client.
//   - owner: repository owner (user or organization).
//   - repo: repository name.
//   - branch: name of the branch to create.
//   - files: map of file paths to file contents to commit.
//
// The function returns an error if any GitHub API operation fails.
func CreatePR(
	ctx context.Context,
	client *github.Client,
	owner, repo, branch string,
	files map[string]string,
) error {

	// Retrieve the reference to the base branch (main).
	// This is used as the starting point for the new branch.
	baseRef, _, err := client.Git.GetRef(ctx, owner, repo, "refs/heads/main")
	if err != nil {
		log.Println("Error getting base ref:", err)
		return err
	}

	// Define a new Git reference (branch) pointing to the same commit
	// SHA as the base branch.
	newRef := &github.Reference{
		Ref: github.String("refs/heads/" + branch),
		Object: &github.GitObject{
			SHA: baseRef.Object.SHA,
		},
	}

	// Create the new branch reference in the repository.
	_, _, err = client.Git.CreateRef(ctx, owner, repo, newRef)
	if err != nil {
		log.Println("Error creating new branch:", err)
		return err
	}

	// Iterate over the provided files and create each one in the new branch.
	for path, content := range files {
		_, _, err := client.Repositories.CreateFile(
			ctx,
			owner,
			repo,
			path,
			&github.RepositoryContentFileOptions{
				Message: github.String("valentine-bot: add " + path),
				Content: []byte(content),
				Branch:  github.String(branch),
				Author: &github.CommitAuthor{
					Name: github.String("valentine-bot"),
				},
				Committer: &github.CommitAuthor{
					Name: github.String("valentine-bot"),
				},
			},
		)
		if err != nil {
			log.Println("Error creating file:", path, err)
			return err
		}
	}

	// Define the pull request metadata.
	pr := &github.NewPullRequest{
		Title: github.String("AI Generated Code"),
		Head:  github.String(branch), // The name of the branch where changes are implemented.
		Base:  github.String("main"), // The branch you want your changes pulled into.
		Body:  github.String("Generated by AI Bot "),
	}

	// Create the pull request.
	_, res, err := client.PullRequests.Create(ctx, owner, repo, pr)
	if res != nil {
		log.Println(res)
	}

	return err
}