package github

import (
	"context"
	"log"
	"github.com/google/go-github/v62/github"
)

func CreatePR(
	ctx context.Context,
	client *github.Client,
	owner, repo, branch string,
	files map[string]string,
) error {

	// 1. Check if branch already exists
	_, _, err := client.Git.GetRef(ctx, owner, repo, "refs/heads/"+branch)
	if err != nil {

		// If NOT found → create branch
		if ghErr, ok := err.(*github.ErrorResponse); ok && ghErr.Response.StatusCode == 404 {

			log.Println("Branch does not exist, creating:", branch)

			// Get base branch (main)
			baseRef, _, err := client.Git.GetRef(ctx, owner, repo, "refs/heads/main")
			if err != nil {
				log.Println("Error getting base ref:", err)
				return err
			}

			newRef := &github.Reference{
				Ref: github.String("refs/heads/" + branch),
				Object: &github.GitObject{
					SHA: baseRef.Object.SHA,
				},
			}

			_, _, err = client.Git.CreateRef(ctx, owner, repo, newRef)
			if err != nil {
				log.Println("Error creating new branch:", err)
				return err
			}

		} else {
			// Real error
			log.Println("Error checking branch:", err)
			return err
		}

	} else {
		// Branch exists
		log.Println("Branch already exists, using:", branch)
	}

	// 2. Create/update files
	for path, content := range files {
		_, _, err := client.Repositories.CreateFile(
			ctx,
			owner,
			repo,
			path,
			&github.RepositoryContentFileOptions{
				Message: github.String("valentine-bot: add " + path),
				Content: []byte(content),
				Branch:  github.String(branch),
				Author: &github.CommitAuthor{
					Name: github.String("valentine-bot"),
				},
				Committer: &github.CommitAuthor{
					Name: github.String("valentine-bot"),
				},
			},
		)
		if err != nil {
			log.Println("Error creating file:", path, err)
			return err
		}
	}

	// 3. Create PR
	pr := &github.NewPullRequest{
		Title: github.String("AI Generated Code"),
		Head:  github.String(branch),
		Base:  github.String("main"),
		Body:  github.String("Generated by AI Bot"),
	}

	_, res, err := client.PullRequests.Create(ctx, owner, repo, pr)
	if res != nil {
		log.Println(res)
	}

	return err
}