package githubclient

import (
	"context"
	"log"

	"github.com/google/go-github/v62/github"
)

func CreatePR(
	ctx context.Context,
	client *github.Client,
	owner, repo, branch string,
	files map[string]string,
) error {

	baseRef,_, err := client.Git.GetRef(ctx, owner, repo, "refs/heads/main")
	if err != nil {
		log.Println("Error getting base ref:", err)
		return err;
	}

	newRef := &github.Reference{
		Ref: github.String("refs/heads/" + branch),
		Object: &github.GitObject{
			SHA: baseRef.Object.SHA,
		},
	}

	client.Git.CreateRef(ctx, owner, repo, newRef)
	for path, content := range files {
		client.Repositories.CreateFile(ctx, owner, repo, path, 
		&github.RepositoryContentFileOptions{
			Message: github.String("valentine-bot: add " + path),
			Content: []byte(content),
			Branch: github.String(branch),
			Author: &github.CommitAuthor{
				Name: github.String("valentine-bot"),
			},
			Committer: &github.CommitAuthor{
				Name: github.String("valentine-bot"),
			},
		})
	}

	pr := &github.NewPullRequest{
		Title: github.String("AI Generated Code"),
		Head:  github.String(branch),
		Base:  github.String("main"),
		Body:  github.String("Generated by AI Bot "),
	}

	
	_, res, err := client.PullRequests.Create(ctx, owner, repo, pr)
	if res != nil {
		log.Println(res)
	}
	
	return err
}
